title: My blog
author:
  name: EMail
  email: ole370@duck.com


description: _A blog is described by its description._


theme: minima
minima:
  skin: solarized-light


plugins:
  - jekyll-feed


header_pages:
  - about.md
