title: My blog
author:
  name: Ole370
  email: ole370@duck.com


description: A blog is described by its description.


theme: minima
minima:
  skin: solarized-light


plugins:
  - jekyll-feed
